#!/bin/sh
echo Combine CSS files...
cat vanilla-terminal.css todo.css > app.css
echo Add vanilla-terminal...
cat polyfills.js vanilla-terminal.es5.js > app.js
echo Compile app.rb...
opal --compile app.rb | grep -v "//# sourceMappingURL" >> app.js
